apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: main
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app.local
    http:
      paths:
       - backend:
           service:
             name: python-app
             port: 
               number: 8080
         path: /
         pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: canary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "${WEIGHT}"
spec:
  rules:
  - host: app.local
    http:
      paths:
       - backend:
           service:
             name: python-app
             port: 
               number: 8080
         path: /
         pathType: Prefix
